### ISSUE TITLE
Options dialog "to be done"

### ISSUE THREAD

**Issue by GitMensch** [javalite/jar-explorer#10]
I just thought I've broken something but it is actually in the code...

I *guess* the Options dialog would have at least the current settings from the configuration in and maybe filtering options.
Is there anything else that comes to mind?

If the option dialog is expected tbd for the next months, too then it would be reasonable to deactivate the menu entry until then.

**Comment by ipolevoy** [comment]
I wrote this tool more than 10 years ago:) Since the Options dialog was never used, I think it is safe to delete it now.
