### ISSUE TITLE
Deleting "bin" and add release instead

### ISSUE THREAD

**Issue by GitMensch** [javalite/jar-explorer#6]
This would show directly which version is available ([0.6-Beta][1], [0.7-Beta][2] and the "new" [0.7][3] can be in as a starting point), highlight the differences (at least the ones that we're aware of) and allows for direct download.

If you're ok with this but don't want to do it then I'm happy to help.

[1]:https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/jar-explorer/jarexplorer-0.6-BETA.jar
[2]:https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/jar-explorer/jarexplorer-0.7-BETA.jar
[3]:https://github.com/javalite/jar-explorer/blob/master/bin/jarexplorer-0.7.jar

**Comment by ipolevoy** [comment]
go ahead

**Comment by GitMensch** [comment]
I currently can't as I have neither write nor release access to this repository :-)

Note: Something like this will happen when I have the access: https://github.com/Bill-Gray/PDCurses/releases, compared with the old repo https://github.com/wmcbrine/PDCurses/releases

**Comment by ipolevoy** [comment]
you can fork and send a pull request, right?

**Comment by GitMensch** [comment]
Only for the "delete/reorder files" part, there are no options of PR releases (at least I don't know of any).

**Comment by ipolevoy** [comment]
I added you to the repo. I do not know how this works on GitHub, go ahead!

**Comment by GitMensch** [comment]
Releases [are in now](https://github.com/javalite/jar-explorer/releases), bin removed via PR (closing here, only the PR needs to be merged and closed by you).

There *must* be something to find that is missing to create the 1.0 release :-)
