### ISSUE TITLE
very minor issue @ipolevoy: you may want to link old commits to your current account

### ISSUE THREAD

**Issue by GitMensch** [javalite/jar-explorer#7]
Feel free to delete if this is non-sense for you, just wanted to highlight it...

Checking https://github.com/javalite/jar-explorer/commits/master everybody sees the email from the account you've used on google code.
This should (theoretically) be replaced by a link to your current account if you add this mail under https://github.com/settings/emails and verify it.

**Comment by ipolevoy** [comment]
hm, where is my email visible? Did not find it.

**Comment by ipolevoy** [comment]
oh,  found it.... It is OK, no longer in use. Thanks for the pointer though

**Comment by GitMensch** [comment]
It still would (should) lead to commits being assigned to your account, but it fine to leave as is.
